VARS_FILES=telmore/environments/aws/common-director/director.yml telmore/environments/aws/sbx/config-director/vars/director.yml interpolated-files/telmore/environments/aws/sbx/config-director/secrets/director.yml
